added new cool stuff

diff --git a/dwnamecrawl b/dwnamecrawl
--- a/dwnamecrawl
+++ b/dwnamecrawl
@@ -1,5 +1,20 @@
 #!/bin/bash
-#Domain
+REGEX="href=\".*:\/\/[A-Za-z0-9_\.-]*\.*\/.*\".*"
+while getopts ":a" opt; do
+  case $opt in
+    h)
+      echo "-f to look for urls in given domain only" >&2
+      stop
+      ;;
+    f)
+      REGEX="href=\".*:\/\/[A-Za-z0-9_\.-]*\.*\/.*\".*"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
+
 if [ $# -eq 0 ]
   then
     echo "ERROR: No arguments supplied"
@@ -8,14 +23,9 @@ if [ $# -eq 0 ]
     echo "USAGE: please enter a domain ex. google.com"
     echo " "
 fi
-# Download landing page
-  wget --no-check-certificate -w2 -np -N -nd -t1 -A '*.html' --limit-rate=20K -r -p -U Mozilla $1
-  #hayder help here need to grep all .html files
-  grep -o '[A-Za-z0-9_\.-]*\.*'$1 ./index.html | sort -u > url.txt
-  for url in $(cat url.txt);do
-        #print ips for urls
-	host $url | grep "has address" | cut -d " " -f4
-  done
+  # Download landing page
+  wget --no-check-certificate -np -N -nd -t1 -A.html -r -p -U Mozilla $1 -P ./tmp/ > /dev/null 2>&1
+  grep -o 'href=".*:\/\/[A-Za-z0-9_\.-]*\.*\/.*".*' ./tmp/* | cut -d'"' -f2 | sort -u
+  
 #cleanup
-rm index.html
-rm url.txt
+rm -rf ./tmp/
